import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "./Component/Navigation/ResponsiveNav";
import Link from "next/link";
import Hero from "./Component/Hero/Hero";
import feature from "./Component/Features/Feature";
import PopularBurger from "./Component/PopularBurger/PopularBurger";

const barlow_Condensed = Barlow_Condensed({ weight: ["300","400","500","600","700","800"],subsets:["latin"] });

export const metadata: Metadata = {
  title: "Burger | A Healthy Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={barlow_Condensed.className}> <ResponsiveNav />  {children}</body>
    </html>
  );
}
